---
- name: install software applications
  hosts: all
  tasks: 
    - name: installation done with global scope variables
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...
