---
- name: create user on all managed nodes
  hosts: all
  tasks:
    - name: user creation
      user:
        name: udaya
        password: udaya@123
        uid: 152
        shell: /bin/bash
        comment: 'normal user'
...
